# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OLDIMGTOOL_COMMIT: dda46823a687f3ac9d7f6ff779a9c550cd45f7f5

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download cached oldimgtool
        id: oldimgtool
        uses: actions/cache@v4
        with:
          path: oldimgtool-${{ env.OLDIMGTOOL_COMMIT }}/target/release/oldimgtool
          key: oldimgtool-${{ env.OLDIMGTOOL_COMMIT }}

      - name: Install cached oldimgtool
        if: steps.oldimgtool.outputs.cache-hit == 'true'
        run: |
          install -m755 oldimgtool-${{ env.OLDIMGTOOL_COMMIT }}/target/release/oldimgtool /usr/local/bin/

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt remove man-db
          sudo apt-get install --no-install-recommends -y clang gcc-arm-none-eabi lld llvm

      - name: Install oldimgtool
        if: steps.oldimgtool.outputs.cache-hit != 'true'
        run: |
          curl -LO https://github.com/justtryingthingsout/oldimgtool/archive/${{ env.OLDIMGTOOL_COMMIT }}.tar.gz
          tar xf ${{ env.OLDIMGTOOL_COMMIT }}.tar.gz
          cd oldimgtool-${{ env.OLDIMGTOOL_COMMIT }}
          cargo build --release
          sudo install -m755 target/release/oldimgtool /usr/local/bin/

      - name: Build
        run: make -k -j$(nproc) CHAINLOADING=1

      - uses: actions/upload-artifact@v4
        with:
          name: mini-haywire
          path: |
            build/mini.img3
